### ISSUE TITLE
arduino firmware is still missing

### ISSUE THREAD

**Issue by lifthoofd** [WorldWilderLab/PlanEt_SMD#1]
the code for the arduino is not yet included

**Comment by ghost** [comment]
Code hasn't changed. We were going to discuss how we can split that work up
?

**Comment by lifthoofd** [comment]
I could push it to this repo as well, it will be next on the things i have
to do. I thought to leave it like this until we have something that we can
put there.

On Tue, Sep 15, 2015 at 1:29 PM, artag notifications@github.com wrote:

> Code hasn't changed. We were going to discuss how we can split that work up
> ?
> 
> On Tue, Sep 15, 2015 at 12:28 PM, Erik notifications@github.com wrote:
> 
> > the code for the arduino is not yet included
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/WorldWilderLab/PlanEt_SMD/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WorldWilderLab/PlanEt_SMD/issues/1#issuecomment-140358963
> .

## 

tel: +31624144454
web: http://www.lifthoofd.nl
email: eovermeire@gmail.com

**Comment by ghost** [comment]
Push it anyway, it's the starting point for new work

**Comment by lifthoofd** [comment]
Am pushing as we speak :)

On Tue, Sep 15, 2015 at 1:32 PM, artag notifications@github.com wrote:

> Push it anyway, it's the starting point for new work
> 
> On Tue, Sep 15, 2015 at 12:31 PM, Erik notifications@github.com wrote:
> 
> > I could push it to this repo as well, it will be next on the things i
> > have
> > to do. I thought to leave it like this until we have something that we
> > can
> > put there.
> > 
> > On Tue, Sep 15, 2015 at 1:29 PM, artag notifications@github.com wrote:
> > 
> > > Code hasn't changed. We were going to discuss how we can split that
> > > work
> > > up
> > > ?
> > > 
> > > On Tue, Sep 15, 2015 at 12:28 PM, Erik notifications@github.com
> > > wrote:
> > > 
> > > > the code for the arduino is not yet included
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/WorldWilderLab/PlanEt_SMD/issues/1.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/WorldWilderLab/PlanEt_SMD/issues/1#issuecomment-140358963
> > 
> > > .
> > 
> > ## 
> > 
> > tel: +31624144454
> > web: http://www.lifthoofd.nl
> > email: eovermeire@gmail.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/WorldWilderLab/PlanEt_SMD/issues/1#issuecomment-140359271
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WorldWilderLab/PlanEt_SMD/issues/1#issuecomment-140359400
> .

## 

tel: +31624144454
web: http://www.lifthoofd.nl
email: eovermeire@gmail.com
